analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.2969925
title: Tuesday Club
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.3131065
  brandStrength: 0.7792696
  rhythmicContrast: 0.9194119
  brandColors:
    - '#030D17'
    - '#6E5D65'
    - '#FBBFB2'
    - '#F29188'
    - '#BB9AA2'
  lightness: 0.1091598
purpose: []
favicon: null
name: Tuesday Club
typography_spectrum: 0.5257788
